### PR TITLE
Update Paella Player to version 6.4.3

### PR DESCRIPTION
**Pull request by mliradelc**
This PR updates Paella player to version 6.4.3

### CODE REVIEW

**Comment by rfcmaXi** [comment]
hey, thanks a lot!!!!!
I've only skimmed this for a short time, but I think the new plugins for the slides and buffered bar are missing?:

es.upv.paella.timeMarksPlaybackCanvasPlugin
https://github.com/polimediaupv/paella/blob/2e4916c39f15e8f1e83418cc7921c66f6588f03e/CHANGELOG#L29
and
es.upv.paella.BufferedPlaybackCanvasPlugin
https://github.com/polimediaupv/paella/blob/2e4916c39f15e8f1e83418cc7921c66f6588f03e/CHANGELOG#L22

**Comment by mliradelc** [comment]
> hey, thanks a lot!!!!!
> I've only skimmed this for a short time, but I think the new plugins for the slides and buffered bar are missing?:
> 
> es.upv.paella.timeMarksPlaybackCanvasPlugin
> https://github.com/polimediaupv/paella/blob/2e4916c39f15e8f1e83418cc7921c66f6588f03e/CHANGELOG#L29
> and
> es.upv.paella.BufferedPlaybackCanvasPlugin
> https://github.com/polimediaupv/paella/blob/2e4916c39f15e8f1e83418cc7921c66f6588f03e/CHANGELOG#L22

Thanks you for notice that!, I've found that the `es.upv.paella.timeMarksPlaybackCanvasPlugin` causes Paella playback bar to crash! I will inform asap the developers about that.

I left the config file without that plugins to left the same options as the developer.

**Comment by rfcmaXi** [comment]
I just cherry-picked your merge and added the two new plugins.
I set "slidesMarks" to false.
Works, nothing crashes for me.

**Comment by mliradelc** [comment]
Where did you put these lines @rfcmaXi ?:
```json
"es.upv.paella.timeMarksPlaybackCanvasPlugin": {
        "enabled": true,
        "color": "gray"
      },
      "es.upv.paella.BufferedPlaybackCanvasPlugin": {
        "enabled": true,
        "color": "rgba(0,0,0,0.4)"
      },
```

Because even if I set `slidesMarks` to false, still crashes the playback bar (No buttons).

**Comment by theodortruffer** [comment]
New PR: #26

**Pull request closed without merging**
