### PR TITLE
Paella player 6.4.5

### PR DESCRIPTION
**Pull request by mliradelc**

### CODE REVIEW

**Comment by samuelinniger** [comment]
+1

@theodortruffer Could this fix the livestreaming Issue for Chrome-Browsers? 
See https://github.com/polimediaupv/paella/issues/657#issuecomment-769198623

**Comment by theodortruffer** [comment]
The plugin beta version (branch feature/3-5_beta) already has v6.4.5 of the player, but we still experienced the Chrome issues. But there seems to be a version 6.5.0 now, with "Improvements in HLS plugin". I'll include this version in the beta branch today and come back to you.

**Comment by theodortruffer** [comment]
@mliradelc @samuelinniger 
The latest paella player version is now in the branch feature/3-5_beta. Could you test this version with a live stream and see if the Chrome issue still occurs?

@samuelinniger you can also test on ikt.ch, the latest version is already installed.

**Comment by mliradelc** [comment]
@theodortruffer I can check that but Polimedia they just released v6.5.0 I will check that


Update: @theodortruffer ~~I tried version 6.5.0 and won't work with the ilias plugin~~ I just saw that the beta has the new paella.

**Comment by mliradelc** [comment]
@theodortruffer  TI'm in the beta branch, Paella player wont work

Screenshot_20210202_165200

With 6.4.5 there is no problem.

**Comment by theodortruffer** [comment]
@mliradelc I see these errors as well, but they should have no effect on the player. It's mostly javascript files trying to be loaded that don't exist anymore (I'm fixing this at the moment). 

Is the player not working at all, or just not working with live streams?

**Comment by mliradelc** [comment]
Unfortunately, not working at all, I tried with Firefox and Chrome :sad:

The error also hints that can't find `hls.min.js` and `base.js` that is very strange

**Comment by theodortruffer** [comment]
base.js should be okay - I was told to look at this file to see what js fiels are required: https://github.com/studer-raimann/OpenCast/blob/feature/3-5_beta/node_modules/paellaplayer/build/player/index.html

Oh, I see the problem now. The player is looking for its files in the wrong directory, because the player is installed in a subdirectory. So it's looking at '/ilias/javascript/...' instead of '/ilias/Customizing/global/......../javascript/..'.
We had the same problem with the '/resources' directory, that's why there's a Workaround in the Readme (creating a symlink). 

I will make another issue at polimediaupv. Meanwhile you could try this workaround if you like:
`ln -s Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/node_modules/paellaplayer/build/player/javascript/ . `
Execute this in the ilias base directory. The idea is to make a symlink, so the hls.js can be found under '/ilias/javascript/hls.min.js'.

**Comment by mliradelc** [comment]
Hi @theodortruffer 

I see!! I had that configured, I think when I changed the branch the symbolic links were deleted. Using your suggestion plus the another symbolic link worked out.

```bash
ln -s Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/node_modules/paellaplayer/build/player/resources/ .
```

Now we will try the livestream :wink:

**Comment by mliradelc** [comment]
Update: With paella 6.5.0 works the live stream.

**Comment by theodortruffer** [comment]
Great! Thanks a lot for testing!
You didn't have the Chrome-related issue though, right?

**Comment by mliradelc** [comment]
From what Ruth said, no, we haven't that issue.

**Comment by mliradelc** [comment]
Closed in favor the 6.5.0 beta branch.

**Pull request closed without merging**
