### PR TITLE
paella player v6.4.3

### PR DESCRIPTION
**Pull request by theodortruffer**

### CODE REVIEW

**Comment by theodortruffer** [comment]
@mliradelc 
I made a feature-branch with paella player v6.4.3 and introduced some fixes that should prevent the new plugins from crashing the playback bar.

It seems to work for me, but I couldn't test it with your installation though (I have your configuration but the player doesn't seem to work at the moment). Do you have the time to test this in the next few days? I will merge it immediately if it works for you too.

**Comment by mliradelc** [comment]
Thanks @theodortruffer I will test it right now.

**Comment by mliradelc** [comment]
Now works with the plugins that I had problems. Thanks, I was never thought about in the way how the plugin was serving the data to paella.

There is one thing that is not working, is the multiple qualities plugin `es.upv.paella.multipleQualitiesPlugin`, but that is easily fix if you add:
```json
...
"minVisibleQuality": 60
...
```
To the parameters list of the plugin.

**Comment by theodortruffer** [comment]
Great, thanks for testing and for the fix i missed! I just merged and released a new version.

(@rfcmaXi FYI, I saw that you were also interested in the other PR)

**Pull request merged**
